version: "3.4"

services:
  dev:
    build: .
    image: ubuntu:yosethegame
    container_name: ubuntu-yosethegame
    environment:
      - MOZ_HEADLESS=1
    ports:
      - 5001:5001
    volumes:
      - ../../package.json:/root/code/package.json
      - ../../package-lock.json:/root/code/package-lock.json
      - ../../node_modules:/root/code/node_modules
      - ../../.nvmrc:/root/code/.nvmrc
      - ../../.gitignore:/root/code/.gitignore
      - ../../.prettierignore:/root/code/.prettierignore
      - ../../about:/root/code/about
      - ../../app:/root/code/app
      - ../../yop:/root/code/yop
