name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: update /etc/hosts
        run: |
          sudo echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
          cat /etc/hosts
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - name: info
        run: |
          node --version
          npm --version
          pwd
          ls -R app
      - name: install
        run: |
          npm install
      - name: tests
        run: |
          npm test
